baseURL = "https://xiaojieluo.com/"
languageCode = "en-us"
title = "Hola"
theme = "simpleness"
pygmentsStyle = "monokai"
author = "Xiaojie Luo"
description = "Developer"

[permalinks]
posts = "/posts/:title/"
about = "/about/"

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  showmonth = true
  slogan = "always make it happen"
  description = "A simple and concise blog."
  disqus = ""

[params.valine]
  enable = true
  lang = 'en' # zh-CN
  appId = '3uutfWHHYBtffLPwlkIKNTk8-gzGzoHsz'
  appKey = 'DqaEXtwYz1E8XHoTykI43xz8'
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true
  enableHeaderVisitor = true
  debug = true

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/xiaojieluo"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula" # github, dracula, vim, monokai
    tabWidth = 4